spring.application.name=MyRestfulProjectTheFirst
#Database config
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/restful_db
spring.datasource.username=${POSTGRES_USERNAME:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}

#Liquibase configuration
spring.liquibase.url=jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB_NAME:restful_db}
spring.liquibase.user=${POSTGRES_USERNAME:postgres}
spring.liquibase.password=${POSTGRES_PASSWORD:postgres}
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.drop-first=false
spring.liquibase.default-schema=public

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true




