create table papers (
    paper_id int generated by default as identity primary key,
    title varchar(100),
    content varchar(1000),
    date_for_publishing timestamp with time zone,
    author_id int references authors(author_id)
)